### ISSUE TITLE
Exam Rank 2: Level 1 exercise "Union" missing subject

### ISSUE THREAD

**Issue by e-cala** [JCluzet/42_GradeMe#26]
There is no attachement folder with the subject of the "Union" Exercise in `.subjects/STUD_PART/exam_02/1/union.`

**Comment by JCluzet** [comment]
Hi @e-cala 👋🏼
If you don't have the union subject it's because the topic UNION was deleted from 42 at exam 03.

So it has been deleted from 42_EXAM.

However if you have an old version of 42_EXAM you may not have the subject anymore.
Just delete the 42_EXAM folder and re-clone it.
This will solve the problem.
